# Generated by Django 6.0.6 on 2026-07-06 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('amount', models.IntegerField()),
                ('picture', models.ImageField(upload_to='product_images/')),
                ('category', models.CharField(max_length=50)),
            ],
        ),
    ]
