# Generated by Django 6.0.6 on 2026-07-06 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='image',
        ),
    ]
